repository: alirezadizaji/alirezadizaji.github.io
version: 1
name: Alireza Dizaji
email: alirezadizaji24@gmail.com
darkmode: true
trigger_darkmode:
  start_light: '05'
  start_dark: '16'
last_updated_time: 10th May 2023
github_username: alirezadizaji
linkedin_username: alireza-dizaji-43a634194
googlescholar_username: rTdeQaMAAAAJ
about_title: About Me
about_profile_image: images/me.jpeg
about_content: |
  **CV: [PDF](https://alirezadizaji.github.io/files/CV.pdf)**

  (**PLEASE NOTE: Sharif CE mail server (*@ce.sharif.edu) has been down since mid-January 2023 without giving any precautions. please be in contact with me via my Gmail or Yahoo.**)

  My name is Alireza Dizaji and I graduated as a Bachelor of Science student
  at the **Sharif University of Technology**, **Computer Engineering** field. 
  I have +3 years of research experience in the fields of computer vision and machine learning; 
  For the last four months, under the supervision of Prof. Rueckert at **Technical University of Munich**, As an Undergrad RA 
  I have been working on human-pose action recognition using spatio-temporal human-skeleton graphs, at the intersection of geometric deep learning and semi-supervised learning.
  From May-Nov 2022, I was a research intern at the **Technical University of Munich** 
  working on explainability in graph neural networks under the co-supervision of Prof. Navab and 
  Prof. Rueckert. For +1.5 years, I was an R&D scientist at CommaMed where on the ML academic side, our main contribution was to tackle the current 
  issues of pooling layers and bring a novel attention-based pooling layer by using weakly-supervised learning, under the supervision of Prof. Rabiee. I also have 1 year of experience 
  in the Reinforcement Learning field working on agent movement within a maze using 
  contrastive learning methods. My research interests are **Computer Vision**, **Geometric Deep Learning**, **Explainable Machine Learning**, and **Causality**.
more_content: |
  Alongside my interests in science and technology, some of my other hobbies are:
    - **Reading books**: I am a big fan of Fantasy books, and mostly
    spend my leisure time reading them. Books are the first things that can help me put my mind away from this world and live through the other ones. Besides, the most joyful and cheapest way of journeying for me is reading books. Here I listed a brief description of my understanding of several of them:
      - <i> J.R.R Tolkien's Valinor, Numenor, and Middle-earth history </i>: I traveled through sir Talkien's universe (and probably ours) by reading his masterpieces, including the <i> Silmarillion </i>, <i> Unfinished Tales </i>, <i> Hobbit </i>, and <i> Lord of the Rings </i> series.
      He represents the life of the Evil and Eru Illuvatar's descendants for three ages with the main subject of standing against the Evil, though we should know ourselves better for this purpose:
        - Envying and the Evil: Basically, There is no Evil, but envying is the thing that creates its root as the Morgoth envied the fair land of Valinor. Directing all your behaviors, including cupidity, towards envying 
        can grow the evil inside yourself. But Evil always loses because instinctively, following evil wills closes one's mind towards the things that potentially could become the first motifs towards 
        its destruction. That's why evil will always end at its starting point. I believe permanently removing jealousy inside ourselves is difficult, but we are the ones choosing how to direct our actions afterward. Besides, we all possess the same good and bad features since we were born, though our choices determine us to become Evil or.
        - Fate: During the story, all are taking a path in their lives, but incredibly these paths are somehow related to each other as they all lead to the same target. One of my main concerns was why we all live in this world. why there should be 8 billion people on the earth? What of it? During the story, sir Tolkien demonstrates a single target: Perishing Evil. This is something that always exists till the end, and 
        the path that one takes determines his side. So the point is these paths are like small intervals that concatenate into a bigger path, one leading to a finite evil end, and the other one to reach infinity. After all, Life's span is short-term, so that's why many people exist to reach the goal of the one path and our final fate.
        - Hope and despair: Basically, there is no despair in life. Despair is created in the human mind to justify laziness and loss. Life always shows a hole in your solution, though you should find and take your step. Overthinking assists you in despair, and that's why we should take more steps in our lives rather than think about the steps.

        At last, I'd like to share the quotes that I encountered during my reading:
          - Gandalf The Grey: Despair is for those who see the end beyond all doubt.
          - Lady Galadriel: Do not trouble your hearts overmuch with the thought of the road. Maybe the paths 
            that you each shall tread are already laid before your feet, though you do not see them.
          - Theoden the King: Evil will shall evil mar: Evil intentions often shall destroy evil itself.
          - Gandalf The Grey: Help comes from the hands of the weak when Wise flattered.
          - Túrin Turambar: Grief is a hone to a hard mind.
          - Sador (Labadal): A man that flies from his fear may find that he has only taken a shortcut to meet it.
      - <i> J.K. Rowling's Harry Potter series </i>: I read all seven books of miss Rowling, and I believe that besides strong imagination and a very friendly world, miss Rowling tried to depict that the only reason for anyone who seeks immortality is to have huge power over all beings. 
      And this is the darkest goal because it is possible only by leaving your pure and single soul, and this could be done only by one action: Split your soul by murdering. By doing so (Like murdering Harry's parents), the seeker automatically creates his enemies 
      and their motivations. You can never seek immortality without making your enemies, that's the point. And you can never perish your enemies because an immense power, e.g. the pure LOVE between mother and son, would be created inside the victims (e.g. Harry) that is impossible to resist against it.
      What's interesting is that Harry maintains this power, but in my opinion, he was very idiot most of the time :). Therefore (same as in Lord of The Rings) there must be people with high wisdom and knowledge (e.g. Dumbledore) to help you employ this motivation and energy very delicately and efficiently. If there are no such people or leaders, 
      then this motivation could also perish very easily because of your silliness.  
      - <i> Andrzej Sapkowski's Witcher series </i>: ...
    - **Watching movies**
    - **Travelling and nature**
content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: AI-Med
        sub_title: R&D scientist
        caption: April 2021 - present
        link: https://aimed-sharif.ir/
        description: |
          AI-Med is a multidisciplinary research consortium **utilizing artificial intelligence
          technologies to improve the quality and accuracy of digital health services**.
          since April 2021, I joined as **research and development scientist** here where
          we have designed a wide-range of deep-learning experiments (via Pytorch) to provide
          better **detection** and **localization** of abnormalities for **mammography screening**.
          our methods have reached and even gone beyond the state-of-the-art algorithms on **public dataset (DDSM)**.
          in order to maintain our results same for the **in-private dataset**, we are currently
          developing **weakly-supervised methods** to more precisely label and generate ground-truth ROIs for them.
          Moreover, we have designed several side tools to get real-time feedbacks from experienced radiologists for labeling. 
      - layout: left
        title: Sharif University of Technology
        sub_title: Research Assistant
        caption: August 2020 - March 2021
        description: |
          I joined [**DML lab**](http://dml.ce.sharif.edu/dmlsite/) as a **Research assistant** where I was working
          on the impact of **contrastive learning** approaches on **deep reinforcement-learning** algorithms.
          to be more specific, I implemented [**CURL**](https://arxiv.org/pdf/2004.04136.pdf?ref=https://githubhelp.com) 
          and [**SIMCLR**](https://arxiv.org/pdf/2002.05709.pdf) (via Pytorch) algorithms to improve movement of an agent
          within Maze environment.
      - layout: left
        title: Sharif University of Technology
        sub_title: Teaching Assistant
        caption: Februrary 2019 - July 2021
        description: |
          since my second semester, I have collaborated as a **teaching assistant** with several
          faculty members of **computer engineering department**. all courses that I have contributed are listed below:

          **Spring 2021**
          - Machine learning (M.Sc. course), Dr. Rohban
          - Modern information retrival, Dr. Soleymani


          **Fall 2020**
          - Artificial intelligence, Dr. Rohban
          - Linear algebra, Prof. Rabiee


          **spring 2020**
          - Computer architecture, Prof. Asadi
          - Data structures and algorithms, Dr. Safarnejad broujeni


          **spring 2019**
          - Advanced programming, Mr. Hatami
  - title: Education
    layout: list
    content:
      - layout: left
        title: Sharif University of Technology
        sub_title: B.Sc. Computer Engineering
        caption: 2017-present
        description: |
          GPA: 17.90/20 (**last six semesters: 18.51/20**)

          **Related courses**

          Convolutional neural networks for visual recognition (audited, online Stanford),
          machine learning (audited, online Stanford), artificial intelligence, linear algebra,
          data structures and algorithms, introduction to bioinformatics, modern information retrieval,
          design of algorithms, probability and statistics, discrete structures.
      - layout: left
        title: Allame Amini highschool
        sub_title: Diploma
        caption: 2013-2017
        description: |
          I received my Diploma in Mathematics and Physics from Allame Amini highschool,
          where I was ranked 24th out of 350k students in Iranian nationwide mathematics
          exam (Konkur).
  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in science and technology, some of my other hobbies are:
        - Reading books: I am a big fan of Fantasy books, and mostly
        spend my leisure time reading them in English. Sometimes I really feel sick of this world, and I'd like to put my mind away from it and live through the others. Besides, for me the most joyful and cheapest way of journeying is reading books:
          - J.R.R Tolkien's Valar, Numenor, and Middle-earth history: I have read the <i> Silmarillion </i>, <i> Unfinished Tales </i>, <i> Hobbit </i>, and <i> Lord of the Rings </i> series of sir Tolkien, traveling through the time, and understanding many things
          like the instinct consequences of envying, seeking the immortality, and forging evil wills. In addition, fates, reasons behind beings of all creatures, and our path in our lives. Seems like we are descendants of the Men, but I prefer to be from Eldar races :(.
          - J.K. Rowling's Harry Potter series: I have read all seven books of the Harry Potter series, understanding again the consequences of seeking immortality, creating your own enemies by oppression, and the hidden power of Love.
          - Andrzej Sapkowski's Witcher series: ...
        - Watching movies
        - Travelling and nature
footer_show_references: false
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - lib/
  - scripts/
  - docker-compose.yml
