repository: alirezadizaji/alirezadizaji.github.io
version: 1
name: Alireza Dizaji
email: alirezadizaji24@gmail.com
darkmode: true
trigger_darkmode:
  start_light: '09'
  start_dark: '21'
last_updated_time: 15th Dec 2022
github_username: alirezadizaji
linkedin_username: alireza-dizaji-43a634194
googlescholar_username: rTdeQaMAAAAJ
about_title: About Me
about_profile_image: images/me.jpeg
about_content: |
  **CV: [PDF](https://alirezadizaji.github.io/files/CV.pdf)**

  My name is Alireza Dizaji and I have recently graduated as a Bachelor of Science student
  at the **Sharif University of Technology**, **Computer Engineering** field. 
  I have +3 years of research experience in the fields of computer vision and machine learning; 
  For the last seven months, I was a research intern at the **Technical University of Munich** 
  working on explainability in graph neural networks under the co-supervision of Prof. Navab and 
  Prof. Rueckert. For +1.5 years, I am working as an R&D scientist at AI-Med where our 
  focus is to solve and enhance current problems of medical imaging, particularly 
  mammography screening, under the supervision of Prof. Rabiee. I also have 1 year of experience 
  in the Reinforcement Learning field working on agent movement within a maze using 
  contrastive learning methods. My research interests are **Learning on Graphs** and **Graph Neural Networks**, 
  **Explainable Machine Learning**, and **Optimization**.
more_content: |
  Alongside my interests in science and technology, some of my other hobbies are:
    - Reading books: I am a big fan of Fantasy books, and mostly
    spent my leisure time reading them. So far, I have read the <i> Hobbit </i>, <i> Lord of the Rings </i> (**My most favorite one**),
    and <i> Harry Potter </i> series in English, and they (particularly the second one) have significantly 
    changed my attitude towards fate, reasons behind our being, and our path in our lives; 
    Indeed after reading them, I experienced how great books could marvelously direct your thought, 
    and I always ask for or suggest such books preferably in the fantasy genre.
    - Watching movies
    - Travelling and nature
content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: AI-Med
        sub_title: R&D scientist
        caption: April 2021 - present
        link: https://aimed-sharif.ir/
        description: |
          AI-Med is a multidisciplinary research consortium **utilizing artificial intelligence
          technologies to improve the quality and accuracy of digital health services**.
          since April 2021, I joined as **research and development scientist** here where
          we have designed a wide-range of deep-learning experiments (via Pytorch) to provide
          better **detection** and **localization** of abnormalities for **mammography screening**.
          our methods have reached and even gone beyond the state-of-the-art algorithms on **public dataset (DDSM)**.
          in order to maintain our results same for the **in-private dataset**, we are currently
          developing **weakly-supervised methods** to more precisely label and generate ground-truth ROIs for them.
          Moreover, we have designed several side tools to get real-time feedbacks from experienced radiologists for labeling. 
      - layout: left
        title: Sharif University of Technology
        sub_title: Research Assistant
        caption: August 2020 - March 2021
        description: |
          I joined [**DML lab**](http://dml.ce.sharif.edu/dmlsite/) as a **Research assistant** where I was working
          on the impact of **contrastive learning** approaches on **deep reinforcement-learning** algorithms.
          to be more specific, I implemented [**CURL**](https://arxiv.org/pdf/2004.04136.pdf?ref=https://githubhelp.com) 
          and [**SIMCLR**](https://arxiv.org/pdf/2002.05709.pdf) (via Pytorch) algorithms to improve movement of an agent
          within Maze environment.
      - layout: left
        title: Sharif University of Technology
        sub_title: Teaching Assistant
        caption: Februrary 2019 - July 2021
        description: |
          since my second semester, I have collaborated as a **teaching assistant** with several
          faculty members of **computer engineering department**. all courses that I have contributed are listed below:

          **Spring 2021**
          - Machine learning (M.Sc. course), Dr. Rohban
          - Modern information retrival, Dr. Soleymani


          **Fall 2020**
          - Artificial intelligence, Dr. Rohban
          - Linear algebra, Prof. Rabiee


          **spring 2020**
          - Computer architecture, Prof. Asadi
          - Data structures and algorithms, Dr. Safarnejad broujeni


          **spring 2019**
          - Advanced programming, Mr. Hatami
  - title: Education
    layout: list
    content:
      - layout: left
        title: Sharif University of Technology
        sub_title: B.Sc. Computer Engineering
        caption: 2017-present
        description: |
          GPA: 17.90/20 (**last six semesters: 18.51/20**)

          **Related courses**

          Convolutional neural networks for visual recognition (audited, online Stanford),
          machine learning (audited, online Stanford), artificial intelligence, linear algebra,
          data structures and algorithms, introduction to bioinformatics, modern information retrieval,
          design of algorithms, probability and statistics, discrete structures.
      - layout: left
        title: Allame Amini highschool
        sub_title: Diploma
        caption: 2013-2017
        description: |
          I received my Diploma in Mathematics and Physics from Allame Amini highschool,
          where I was ranked 24th out of 350k students in Iranian nationwide mathematics
          exam (Konkur).
  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in science and technology, some of my other hobbies are:
        - Reading books: I am a big fan of Fantasy books, and mostly
        spent my leisure time reading them. So far, I have read the <i> Hobbit </i>, <i> Lord of the Rings </i> (**My most favorite one**)
        and <i> Harry Potter </i> series in English, and they (particularly the second one) have significantly 
        changed my attitude towards fate, reasons behind our being, and our path in our lives; 
        Indeed after reading them, I experienced how great books could marvelously direct your thought, 
        and I always ask for or suggest such books preferably in the fantasy genre.  
        - Watching movies
        - Travelling and nature
footer_show_references: false
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - lib/
  - scripts/
  - docker-compose.yml
